main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('groups/', views.groups_index, name='index'),
    path('groups/<int:group_id>/', views.groups_detail, name='detail'),
    path('groups/create/', views.GroupCreate.as_view(), name='groups_create'),
    path('groups/<int:pk>/update/', views.GroupUpdate.as_view(), name='groups_update'),
    path('groups/<int:pk>/delete/', views.GroupDelete.as_view(), name='groups_delete'),
    path('groups/<int:group_id>/add_idea/', views.add_idea, name='add_idea'),
    path('groups/<int:group_id>/ideas/<int:pk>/delete/', views.IdeaDelete.as_view(), name='ideas_delete'),
    path('groups/<int:group_id>/choose_random_idea/', views.choose_random_idea, name='choose_random_idea'),
    path('groups/<int:group_id>/add_photo/', views.add_photo, name='add_photo'),
]

what_is_the_plan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

ENVIRONMENTS = (
    ('A', 'Anywhere'),
    ('I', 'Inside'),
    ('O', 'Outside')
)

class Group(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'group_id': self.id})
    
    class Meta:
        ordering = ['name']
    
class Idea(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    estimated_time = models.IntegerField(default=0)
    estimated_cost = models.IntegerField(default=0)
    day_of_week = models.CharField(max_length=20, default=' ')
    environment = models.CharField(max_length=1, choices=ENVIRONMENTS, default=ENVIRONMENTS[0][0], blank=True)

    group = models.ForeignKey(Group, on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']
        
    def __str__(self):
        return f"{self.name}"
    
class Photo(models.Model):
    url = models.CharField(max_length=200)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for group_id: {self.group_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Group
from .models import Idea

class CreateGroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ['name']

class IdeaForm(ModelForm):
    class Meta:
        model = Idea
        fields = ['name', 'environment', 'estimated_cost']

main_app/views.py
import uuid
import boto3
import os
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import View
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import random

from .models import Group, Idea, Photo
from .forms import CreateGroupForm
from .forms import IdeaForm

def home(request):
    return render(request, 'home.html')

@login_required
def groups_index(request):
    groups = Group.objects.all()
    return render(request, 'groups/index.html', {'groups': groups})

@login_required
def groups_detail(request, group_id):
    group = Group.objects.get(id=group_id)
    idea_form = IdeaForm()
    return render(request, 'groups/detail.html', { 'group': group, 'idea_form': idea_form })

@login_required
def add_idea(request, group_id):
    form = IdeaForm(request.POST)
    if form.is_valid():
        new_idea = form.save(commit=False)
        new_idea.group_id = group_id 
        new_idea.save()
    return redirect('detail', group_id=group_id)

@login_required
def choose_random_idea(request, group_id):
    group = Group.objects.get(id=group_id)
    ideas = Idea.objects.filter(group=group_id)
    random_idea = random.choice(ideas)
    idea_form = IdeaForm()
    return render(request, 'groups/detail.html', { 'group': group, 'idea_form': idea_form, 'random_idea': random_idea })

@login_required
def add_photo(request, group_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            print("add photo view function")
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, group_id=group_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', group_id=group_id) 

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

class GroupCreate(LoginRequiredMixin, CreateView):
    model = Group
    fields = ['name']

    def form_valid(self, form):
        form.instance.user = self.request.user  

        return super().form_valid(form)
    
class GroupUpdate(LoginRequiredMixin, UpdateView):
    model = Group
    fields = ['name']
    
class GroupDelete(LoginRequiredMixin, DeleteView):
    model = Group
    success_url = '/groups'

class IdeaDelete(LoginRequiredMixin, View): 
    def get(self, request, *args, **kwargs):
        idea = Idea.objects.get(id=kwargs['pk'])
        idea.delete()
        return redirect('detail', group_id=kwargs['group_id'])

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>What's The Plan?!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script type = "text/javascript"  
        src = "https://code.jquery.com/jquery-2.1.1.min.js"></script>    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
</head>
<body class="teal lighten-4">
    <nav class="teal darken-w">
        <div class="nav-wrapper teal darken-w">
            <a href="/" class="brand-logo left">What is the plan?!</a>  
            <a href=" " data-target="mobile-demo" class="sidenav-trigger right"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'index' %}">View All Groups</a>
                </li>
                <li><a href="{% url 'groups_create' %}">Add your Group</a></li>
                <li><a href="{% url 'logout' %}">Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Log In</a></li>
                {% endif %}
            </ul>
            <ul class="sidenav" id="mobile-demo">
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'index' %}">View All Groups</a>
                </li>
                <li><a href="{% url 'groups_create' %}">Add your Group</a></li>
                <li><a href="{% url 'logout' %}">Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer class="teal lighten-3">
        <div class="right-align">© Katherine Sprague 2023</div>
    </footer>

    <script>
        $(document).ready(function(){
    $('.sidenav').sidenav();
    });
    </script>
</body>
</html>

main_app/templates/groups/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="card center">

    <div class="card-action">
        <h1 class="group-name">{{ group.name }}</h1>
        {% if user.id == group.user.id %}
        <a href="{% url 'groups_update' group.id %}">Edit Group</a>
        <a href="{% url 'groups_delete' group.id %}">Delete Group</a>
        {% endif %}
    </div>
</div>

<div class="col s6">
    <table class="striped">

        <thead>
            <h2 class="center">Our Hangout Ideas!</h2>
            <tr>
                <th>Name</th>
                <th>Environment</th>
                <th>Estimated Cost</th>
            </tr>
        </thead>

        <tbody>
            {% for idea in group.idea_set.all %}
            <tr>
                <td>{{idea.name}}</td>
                <td>{{idea.get_environment_display}}</td>
                <td>{{idea.estimated_cost}}</td>

                <td><a href="{% url 'ideas_delete' group.id idea.id %}">Delete Idea</a></td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="center">
        {% if group.idea_set.all|length > 1%}
        <a class="btn" href="{% url 'choose_random_idea' group.id %}">Pick Your Plan at Random!</a>
        {% endif %}
        {% if random_idea %}
        <div class="card-panel">
            
            <h4 class="teal-text text-darken-2">🎉 {{random_idea.name}} 🎉</h4>
            <h5 class="teal-text text-darken-2">Here's your plan that was randomly chosen for you.. Head out and have fun 🙃 </h5>
        </div>
        {% endif %}
        


    </div>

    <h3 class="center">What's your idea? Add it here!</h3>
    <form action="{% url 'add_idea' group.id%}" method="POST">
        {% csrf_token %}
        {{ idea_form.as_p }}
        <input type="submit" class="btn" value="Add Idea">
    </form>
</div>

    {% for photo in group.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' group.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <br><br>
        <button type="submit" class="btn">Upload Photo</button>
    </form>

<script>
    const selectEl = document.querySelectorAll('select');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/groups/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Find Your Group</h1>

{% for group in groups %}
<div class="card-panel">
    <a href="{% url 'detail' group.id %}">
        <div class="teal-text text-darken-2">
            <h3>{{ group.name }}</h3>
        </div>
    </a>
</div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}


<div class="home-page center">
    <h1>What Is The Plan?!</h1>
    <p class="flow-text">An app created to help you and your crew choose a hangout idea at random and without bias.</p>
    <p class="flow-text">Ready to make plans with your crew?</p>
    <p class="flow-text"><span><a href="{% url 'login' %}" class="teal-text text-darken-2">Log
                In</a></span> or <span><a href="{% url 'signup' %}" class="teal-text text-darken-2">Sign
                Up</a></span> Now!! </p>
</div>

{% endblock %}

main_app/templates/main_app/group_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Group</h1>

    <h4>Are you sure you want to delete <span class="teal-text text-darken-2">{{ object.name }}</span>?</h4>

    <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' group.id %}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/group_form.html
{% extends 'base.html' %}

{% block content %}


{% if object %}
<h1>Edit <span class="teal-text text-darken-2">{{object.name}}</span></h1>
{% else %}
<h1>Add Group</h1>
{% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>
    {% endblock %}